export const PRODUCT_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  SOLD_OUT: 'SOLD_OUT',
  ARCHIVED: 'ARCHIVED',
}

export const CONDITION = {
  NEW: 'NEW',
  SECOND: 'SECOND',
}

export const INTEREST_TYPE = {
  WHATSAPP_CLICK: 'WHATSAPP_CLICK',
  MARKETPLACE_CLICK: 'MARKETPLACE_CLICK',
}

export const ACTIVITY_TYPE = {
  PRODUCT_PUBLISHED: 'PRODUCT_PUBLISHED',
  PRODUCT_EDITED: 'PRODUCT_EDITED',
  STORE_UPDATED: 'STORE_UPDATED',
}